version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
      java: latest # Change based on your app's Node.js version
    commands:
      - echo Installing dependencies...
      - npm install -g
      - npm install aws-cdk-lib constructs
      # - npm install -g serverless@3.34.0
      - npm install -g aws-cdk
  pre_build:
    commands:
      - echo Running lint and tests...
      - npm run lint || true # optional: allow lint errors without breaking build
      - npm test || echo "Tests failed but continuing" # remove ||... to fail on test errors

  build:
    commands:
      - echo Building the application...
      # - npm run build # Replace with your build command if different
      - cdk synth
      # - cdk bootstrap
      - cdk deploy --require-approval never

#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - echo Uploading artifacts or performing post-build tasks...

# artifacts:
#   files:
#     - '**/*'  # Include all files in the output artifact, customize as needed
  # base-directory: dist # Change to your build output directory (e.g., build, dist)
